[package]
name = "test-crate"
version = "0.1.0"
authors = ["Sulaiman AlIbrahim <sam-ka@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
